name: Publish

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
            
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Install oboe
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/malb/oboe.git

      - name: Generate HTML through oboe
        run: |
          mkdir out
          cp -r static/* out/
          oboe -e -t templates/template.html data/Data\ Sharing\ Network -o out/nodes

      - name: Publish
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
